name: CI/CD Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t breast-cancer-api .

      - name: Test API endpoint
        run: |
          docker run -d -p 5000:5000 --name test-api breast-cancer-api
          sleep 10
          curl -X GET http://localhost:5000/
          docker stop test-api
          docker rm test-api

      - name: Push Docker image
        run: |
          docker tag breast-cancer-api ${{ secrets.DOCKER_USERNAME }}/breast-cancer-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/breast-cancer-api:latest
